[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bounty_manager = "5bjKDPsreaQrZ2dNoyDbHsUwqJukmDMi5qQheYHVFzD4"

[programs.devnet]
bounty_manager = "5bjKDPsreaQrZ2dNoyDbHsUwqJukmDMi5qQheYHVFzD4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
